class Commands:
    LEECH = "leech"
    PURGE = "purge"
    PAUSEALL = "pauseall"
    RESUMEALL = "resumeall"
    STATUS = "status"
    SETTINGS = "set"
    EXEC = "exec"
    UPLOAD = "upload"
    YTDL = "ytdl"
    PYTDL = "pytdl"
    ABOUT = "about"
    GETLOGS = "getlogs"
    SERVER = "stats"
    USERSETTINGS = "uset"
    INSTADL = "igdl"
