class Commands:
    LEECH = "mediashare"
    PURGE = "purge"
    PAUSEALL = "pause"
    RESUMEALL = "resume"
    STATUS = "status"
    SETTINGS = "settings"
    EXEC = "exec"
    UPLOAD = "upload"
    YTDL = "ytdl"
    PYTDL = "pytdl"
    ABOUT = "about"
    GETLOGS = "log"
    SERVER = "idiot"
    USERSETTINGS = "usettings"
    INSTADL = "igdl"
